from mongoengine import connect
from .constant import (
    DATABASE_PORT,
    DATABASE_HOST,
    DATABASE_USERS,
    DATABASE_TRANSACTIONS,
    DATABASE_RESOURCES,
    DATABASE_LOGS
)

def init_db():
    connect(alias=DATABASE_USERS, db=DATABASE_USERS, host=DATABASE_HOST, port=DATABASE_PORT)
    connect(alias=DATABASE_LOGS, db=DATABASE_LOGS, host=DATABASE_HOST, port=DATABASE_PORT)
    connect(alias=DATABASE_TRANSACTIONS, db=DATABASE_TRANSACTIONS, host=DATABASE_HOST, port=DATABASE_PORT)
    connect(alias=DATABASE_RESOURCES, db=DATABASE_RESOURCES, host=DATABASE_HOST, port=DATABASE_PORT)
